### ISSUE TITLE
Following installation, get error : ModuleNotFoundError : No Module name 'evdev'

### ISSUE THREAD

**Issue by computamike** [alex-s-v/10moons-driver#2]
Have run pip3 install -r requirements, but this error is shown.  Pip does show that the module is inatalled.  

Have also test this in python2

**Comment by alex-s-v** [comment]
Hello. I suggest you try [this repo](https://github.com/jgobi/10moons-driver-t503). Apparently my solution works only on arch-like distributions or something like that (I didn't investigate any further, because I have no time at the moment). If suggested repo will give errors to I will look at what I can do. Good luck!

**Comment by computamike** [comment]
I managed to resolve the issue - this was on Ubuntu 19.xx - i found that if I ran the pip install as sudo, then I could run the driver as sudo also.

**Comment by alex-s-v** [comment]
I'm glad that you solved your problem. Congrats!
